proxmox_host: "10.0.0.1"
proxmox_node: "pve-01"

vm_list:
  - proxmox_host: "{{ proxmox_host }}"
    proxmox_node: "{{ proxmox_node }}"
    vmid: 110
    vm_name: "ubuntu-cloud"
    token_user: "{{ token_user}}"
    token_name: "{{ token_name}}"
    token_secret: "{{ token_secret}}"
    storage_disk_location: "Pool01"
    cloudinit_disk_location: "Pool01"
    snippets_location: "cephfs"
    qcow2_image: "/mnt/pve/cephfs/import/20260228_jammy-server-cloudimg-amd64.qcow2"
    disk_size_increase: "+7G"
    user_data_file: "user-data-ubuntu.yml"
    vendor_data_file: "vendor-data.yml"
    network_data_file: "network-data.yml"

  - proxmox_host: "{{ proxmox_host }}"
    proxmox_node: "{{ proxmox_node }}"
    vmid: 111
    vm_name: "debian-cloud"
    token_user: "{{ token_user}}"
    token_name: "{{ token_name}}"
    token_secret: "{{ token_secret}}"
    storage_disk_location: "Pool01"
    cloudinit_disk_location: "Pool01"
    snippets_location: "cephfs"
    qcow2_image: "/mnt/pve/cephfs/import/debian-13-generic-amd64-20260220-2394.qcow2"
    disk_size_increase: "+8G"
    user_data_file: "user-data-debian.yml"
    vendor_data_file: "vendor-data-ubuntu.yml"
    network_data_file: "network-data-ubuntu.yml"