services:
  packer:
    # image: registry.urios.local/devops/urios_packer:latest
    build:
      context: docker/packer
      dockerfile: Dockerfile
    entrypoint: ["sleep", "infinity"]
    environment:
      - PACKER_PLUGIN_PATH=/workspace/.packer.d/plugins
      - PROXMOX_URL=https://10.0.0.1:8006/api2/json
      - PROXMOX_USERNAME=root@pam!lab
      - PROXMOX_TOKEN=526ef3a0-d2e0-46fd-a4e3-83076a3a7c8d
    volumes:
      - .:/workspace/