apache_mods_enabled:
  - proxy_fcgi
  - proxy_http
  - proxy
  - rewrite
  - deflate
  - expires
  - ssl
  - cache
  - headers
  - http2
  - mpm_event

apache_mods_disabled:
  - mpm_prefork
  - php5.6
  - php7.0
  - php7.1
  - php7.2
  - php7.3
  - php7.4
  - php8.0
  - php8.1
  - php8.2
  - php8.3