#SPDX-License-Identifier: MIT-0
---
# tasks file for create_VM_proxmox
- name: Boucle sur toutes les VMs à créer
  ansible.builtin.include_tasks: create_vm.yml
  loop: "{{ vm_list }}"
  loop_control:
    loop_var: vm
